Admin_Disclaimer_data_show:
    pattern: /show
    defaults: { _controller: RudakDisclaimerBundle:Admin:show }

Admin_Disclaimer_data_edit:
    pattern: /edit
    defaults: { _controller: RudakDisclaimerBundle:Admin:edit }

Admin_Disclaimer_data_update:
    pattern: /update
    defaults: { _controller: RudakDisclaimerBundle:Admin:update }